services:
  php:
    image: urcb/wp-sqlite:latest
    container_name: wp_php
    volumes:
      - wp_root:/var/www/html
      - ./database:/var/www/html/wp-content/database
    restart: always
    networks:
      - wp_net

  nginx:
    image: nginx:alpine
    container_name: wp_nginx
    volumes:
      - wp_root:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - wp_net

networks:
  wp_net:

volumes:
  wp_root: